version: '3'
services:
    python-app:
        build: 
            context: ./python-app
            args: 
                redisport: 6379
                redishost: redis-test
                heartbeatinterval: 1.0
    redis-test:
        build:
            context: ./redis
        ports: 
            - "6380:6379"