version: "3.7"
services:
  consul:
    image: consul:latest
    ports: 
      - "8500:8500"
    # command: consul agent -dev -enable-script-checks -node=web -ui
    volumes:
      - ./scripts:/consul/config