version: '3'
services:
  coredns:
    build:
      context: ./coredns
      dockerfile: Dockerfile
    ports:
      - 53:53/tcp
      - 53:53/udp
  webapi:
    build:
      context: ./webapi
      dockerfile: Dockerfile
    ports:
      - 81:80