version: "3.9"
services:

    mock-api:
      image: rodolpheche/wiremock
      restart: always
      ports:
        # HTTP
        - "8080:8080" 
        # HTTPS
        # - "8443:8443"
      volumes:
        - ./wiremock:/home/wiremock
