- name: This is a hello-world example
  hosts: all
  vars:
    blobvar: "caleblob"
  tasks:
  - debug: var=playbook_dir
  - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
    copy:
      content: "hello world\n"
      dest: /tmp/testfile.txt
  - debug: var=blobvar
  - name: Run ls on target
    command: ls
    register: string_for_later
  - debug: var=string_for_later.stdout

- name: debug step
  hosts: "{{ variable_host | default('localhost') }}"
  tasks:
   - debug:
       msg: "bloop"