# This is a basic workflow to help you get started with Actions

name: ChoreHelper Continuous Integration

on: 
  push: 
    branches: [ main ]
    paths:
    - 'Docker Compose/ChoreHelper/**'
  pull_request:
    paths:
    - 'Docker Compose/ChoreHelper/**'
  workflow_dispatch:

jobs:
  api-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dotnet: [ '5.0.x' ]

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Install dependencies
      working-directory: 'Docker Compose/ChoreHelper/'
      run: dotnet restore ./apps/webapi

    - name: Build
      working-directory: 'Docker Compose/ChoreHelper/'
      run: dotnet build --configuration Release --no-restore ./apps/webapi

  ui-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [15.x, 16.x] # With Angular v12 there is no longer support for Node.js version of < 15

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Clean Install
      working-directory: ./Docker Compose/ChoreHelper/apps/choreui
      run: npm ci

    - name: Build
      working-directory: ./Docker Compose/ChoreHelper/apps/choreui
      run: npm run build --if-present

    # - name: Test
    #   working-directory: ./Docker Compose/ChoreHelper/apps/choreui
    #   run: npm test

  integration-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    
    - name: Compose Integration
      working-directory: ./Docker Compose/ChoreHelper
      run: docker-compose -f docker-compose-full-integration.yml up -d
      
    - name: Integration Test
      working-directory: ./Docker Compose/ChoreHelper
      run: newman run ./tests/Chores.postman_collection.json
